version: '3.8'

services:

  # Base de donn√©es MySQL
  student-mysql:
    image: mysql:8
    container_name: student-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
    ports:
      - "3306:3306"
    networks:
      - student-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 10s
      retries: 10
      start_period: 30s

  # Application Spring Boot
  student-app:
    image: student-management-app:1.0
    container_name: student-app
    depends_on:
      student-mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://student-mysql:3306/studentdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8089
      SERVER_SERVLET_CONTEXT_PATH: /student
    ports:
      - "8089:8089"
    networks:
      - student-network

networks:
  student-network:
    driver: bridge
